
ARCHFLAGS	?= -mmacosx-version-min=10.6 -arch x86_64 -arch i386

CFLAGS 		:= $(ARCHFLAGS) -Wall -O3 -ftree-vectorize
CXXFLAGS  	:= $(CFLAGS)

LDFLAGS		:= $(ARCHFLAGS)
PLUGIN_LDFLAGS	  := -dynamiclib -exported_symbols_list vamp/vamp-plugin.list

VAMPSDK_DIR := ../vamp-plugin-sdk

PLUGIN_EXT := .dylib

include Makefile.inc

