
CFLAGS := -Wall -O3 -fPIC -I../vamp-plugin-sdk/
#CFLAGS := -g -fPIC -I../vamp-plugin-sdk

CXXFLAGS := $(CFLAGS)

PLUGIN_LDFLAGS := -shared -Wl,--version-script=vamp/vamp-plugin.map

VAMPSDK_DIR := ../vamp-plugin-sdk

PLUGIN_EXT := .so

include Makefile.inc

